### ISSUE TITLE
/usr/bin/ld: cannot find -lrapidJSON_api

### ISSUE THREAD

**Issue by ximply** [tengattack/go-rapidjson#1]
# go run basic.go 
# github.com/tengattack/go-rapidjson
/usr/bin/ld: cannot find -lrapidJSON_api
collect2: ld returned 1 exit status

**Comment by tengattack** [comment]
You can go into `rapidjson-wrapper` folder and try run:

```sh
make
cp librapidJSON_api.a ../
```

**Comment by ximply** [comment]
well, tks, but may be my gcc is too old(4.4.7), when run make:
g++ -I. -O3 -c rapidJSON_api.cpp -std=c++11
cc1plus: error: unrecognized command line option "-std=c++11"
make: *** [build] Error 1
